AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'dmpmiddleware.ca.unileversolutions

  Sample SAM Template for dmpmiddleware.ca.unileversolutions

  '
Globals:
  Function:
    Timeout: 60
    Runtime: python3.7
Parameters:
  ENV:
    Description: Required. The env
    Type: String
Resources:
  dmpmiddlewareDoveDryShampoosOlderWyngVersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://serverlesstutorial1/69a17d8b1fd18ba3e76100469638cbcb
      FunctionName:
        Fn::Sub: dmpmiddlewaredove-dry-shampoos-${ENV}
      Handler: main.lambda_handler
      Events:
        doveDryShampoosOlderWyngVersion:
          Type: Api
          Properties:
            Path: /dmpmiddleware-dove-dry-shampoos-data
            Method: post
Outputs:
  doveDryShampoosOlderWyngVersionApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ENV}/dove_dry_shampoos_campaign_data/
