AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    dmpmiddleware.ca.unileversolutions

    Sample SAM Template for dmpmiddleware.ca.unileversolutions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 60
        Runtime: python3.7

Parameters:
    ENV:
        Description: 'Required. The env'
        Type: 'String'


Resources:

    dmpmiddlewareDoveDryShampoosOlderWyngVersionFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: dove_dry_shampoos_older_wyng_version/
            FunctionName: !Sub dmpmiddlewaredove-dry-shampoos-${ENV} 
            Handler: main.lambda_handler
            Events:
                doveDryShampoosOlderWyngVersion:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /dmpmiddleware-dove-dry-shampoos-data
                        Method: post

Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    doveDryShampoosOlderWyngVersionApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ENV}/dove_dry_shampoos_campaign_data/"

    # HelloWorldFunction:
    #   Description: "Hello World Lambda Function ARN"
    #   Value: !GetAtt HelloWorldFunction.Arn

    # HelloWorldFunctionIamRole:
    #   Description: "Implicit IAM Role created for Hello World function"
    #   Value: !GetAtt HelloWorldFunctionRole.Arn
